/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'customerName' : string,
  'date' : string,
  'totalAmount' : bigint,
  'items' : Array<BillItem>,
}
export interface BillItem {
  'rate' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'amount' : bigint,
}
export interface Shopkeeper {
  'id' : bigint,
  'joinDate' : string,
  'name' : string,
  'shopName' : string,
  'phone' : string,
}
export interface StockItem { 'qty' : bigint, 'productId' : string }
export interface _SERVICE {
  'addShopkeeper' : ActorMethod<[string, string, string, string], Shopkeeper>,
  'addStock' : ActorMethod<[string, bigint], undefined>,
  'deductStock' : ActorMethod<[string, bigint], undefined>,
  'getAllBills' : ActorMethod<[], Array<Bill>>,
  'getAllShopkeepers' : ActorMethod<[], Array<Shopkeeper>>,
  'getAllStock' : ActorMethod<[], Array<StockItem>>,
  'getBill' : ActorMethod<[bigint], Bill>,
  'getShopkeeperCount' : ActorMethod<[], bigint>,
  'getStock' : ActorMethod<[string], bigint>,
  'saveBill' : ActorMethod<[bigint, Bill], undefined>,
  'setStock' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];