/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BillItem = IDL.Record({
  'rate' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const Bill = IDL.Record({
  'customerName' : IDL.Text,
  'date' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(BillItem),
});

export const idlService = IDL.Service({
  'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getBill' : IDL.Func([IDL.Nat], [Bill], ['query']),
  'saveBill' : IDL.Func([IDL.Nat, Bill], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BillItem = IDL.Record({
    'rate' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const Bill = IDL.Record({
    'customerName' : IDL.Text,
    'date' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(BillItem),
  });
  
  return IDL.Service({
    'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getBill' : IDL.Func([IDL.Nat], [Bill], ['query']),
    'saveBill' : IDL.Func([IDL.Nat, Bill], [], []),
  });
};

export const init = ({ IDL }) => { return []; };